# Configuration for tuning of the collider
config_collider:

  config_knobs_and_tuning:
    knob_settings:
      # Orbit knobs
      on_x1: 250 # [urad]
      on_sep1: 0 # [mm]
      on_x2: -170 # [urad]
      on_sep2: 0.138 # 0.1443593672910653 # 0.138 # [mm]
      on_x5: 250 # [urad]
      on_sep5: 0 # [mm]
      on_x8h: 0.0
      on_x8v: 170
      on_sep8h: -0.01 # different from 0 so that the levelling algorithm is not stuck
      on_sep8v: 0.01 # idem
      on_a1: 0 # [urad]
      on_o1: 0 # [mm]
      on_a2: 0 # [urad]
      on_o2: 0 # [mm]
      on_a5: 0 # [urad]
      on_o5: 0 # [mm]
      on_a8: 0 # [urad]
      on_o8: 0 # [mm]
      on_disp: 1 # Value to choose could be optics-dependent

      # Crab cavities
      on_crab1: -190 # [urad]
      on_crab5: -190 # [urad]

      # Magnets of the experiments
      on_alice_normalized: 1
      on_lhcb_normalized: 1
      on_sol_atlas: 0
      on_sol_cms: 0
      on_sol_alice: 0

      # RF voltage and phases
      vrf400: 16.0 # [MV]
      lagrf400.b1: 0.5 # [rad]
      lagrf400.b2: 0. # [rad]

      # Octupoles
      i_oct_b1: 60. # [A]
      i_oct_b2: 60. # [A]

    closed_orbit_correction:
      lhcb1: correction/corr_co_lhcb1.json
      lhcb2: correction/corr_co_lhcb2.json

    # Tunes and chromaticities
    qx:
      lhcb1: 62.316
      lhcb2: 62.316
    qy:
      lhcb1: 60.321
      lhcb2: 60.321
    dqx:
      lhcb1: 15
      lhcb2: 15
    dqy:
      lhcb1: 15
      lhcb2: 15

    # Linear coupling
    delta_cmr: 0.001
    delta_cmi: 0.0

    knob_names:
      lhcb1:
        q_knob_1: kqtf.b1
        q_knob_2: kqtd.b1
        dq_knob_1: ksf.b1
        dq_knob_2: ksd.b1
        c_minus_knob_1: c_minus_re_b1
        c_minus_knob_2: c_minus_im_b1
      lhcb2:
        q_knob_1: kqtf.b2
        q_knob_2: kqtd.b2
        dq_knob_1: ksf.b2
        dq_knob_2: ksd.b2
        c_minus_knob_1: c_minus_re_b2
        c_minus_knob_2: c_minus_im_b2

  config_beambeam:
    bunch_spacing_buckets: 10
    num_slices_head_on: 11
    num_long_range_encounters_per_side:
      ip1: 25
      ip2: 20
      ip5: 25
      ip8: 20
    sigma_z: 0.0761
    num_particles_per_bunch: 131665257650.61247
    nemitt_x: 2.5e-6
    nemitt_y: 2.5e-6
    mask_with_filling_pattern:
      pattern_fname: 
        ../filling_scheme/25ns_2228b_2216_1686_2112_hybrid_8b4e_2x56b_25ns_3x48b_12inj_with_identical_bunches.json
      i_bunch_b1: 1147 # If not specified, the bunch with the worst schedule is chosen
      i_bunch_b2: 1147 # Same. A value for i_bunch_b1 and i_bunch_b2 must be specified if pattern_fname is specified

    num_particles_per_bunch_after_optimization: 163001444781.21497
    luminosity_ip1_5_after_optimization: 4.999976881250687e+34
    luminosity_ip2_after_optimization: 0.0
    luminosity_ip8_after_optimization: 0.0
  skip_leveling: false
  config_lumi_leveling:
    ip2:
      separation_in_sigmas: 5
      plane: x
      impose_separation_orthogonal_to_crossing: false
      knobs:
      - on_sep2
      bump_range:
        lhcb1:
        - e.ds.l2.b1
        - s.ds.r2.b1
        lhcb2:
        - s.ds.r2.b2
        - e.ds.l2.b2
      preserve_angles_at_ip: true
      preserve_bump_closure: true
      corrector_knob_names:
        # to preserve angles at ip
      - corr_co_acbyvs4.l2b1
      - corr_co_acbyhs4.l2b1
      - corr_co_acbyvs4.r2b2
      - corr_co_acbyhs4.r2b2
        # to close the bumps
      - corr_co_acbyvs4.l2b2
      - corr_co_acbyhs4.l2b2
      - corr_co_acbyvs4.r2b1
      - corr_co_acbyhs4.r2b1
      - corr_co_acbyhs5.l2b2
      - corr_co_acbyvs5.l2b2
      - corr_co_acbchs5.r2b1
      - corr_co_acbcvs5.r2b1

      num_colliding_bunches: 1686
      final_on_sep2h: -0.1452338095091529
      final_on_sep2v: 8.893005997168027e-18
    ip8:
      luminosity: 2.0e+33
      num_colliding_bunches: 2112 # This will be set automatically according to the filling scheme 
      impose_separation_orthogonal_to_crossing: true
      knobs:
      - on_sep8h
      - on_sep8v
      bump_range:
        lhcb1:
        - e.ds.l8.b1
        - s.ds.r8.b1
        lhcb2:
        - s.ds.r8.b2
        - e.ds.l8.b2
      preserve_angles_at_ip: true
      preserve_bump_closure: true
      corrector_knob_names:
        # to preserve angles at ip
      - corr_co_acbyvs4.l8b1
      - corr_co_acbyhs4.l8b1
      - corr_co_acbyvs4.r8b2
      - corr_co_acbyhs4.r8b2
        # to close the bumps
      - corr_co_acbyvs4.l8b2
      - corr_co_acbyhs4.l8b2
      - corr_co_acbyvs4.r8b1
      - corr_co_acbyhs4.r8b1
      - corr_co_acbcvs5.l8b2
      - corr_co_acbchs5.l8b2
      - corr_co_acbyvs5.r8b1
      - corr_co_acbyhs5.r8b1

      final_on_sep8h: -0.02063184205760766
      final_on_sep8v: 0.016333094051152342
  config_lumi_leveling_ip1_5:
    luminosity: 5.0e+34
    num_colliding_bunches: 2216   # This will be set automatically according to the filling scheme
    vary:
    - num_particles_per_bunch
    constraints:
      max_intensity: 2.3e11
      max_PU: 165

# Configuration for the track job
config_simulation:

  # Collider file
  collider_file: ../1_build_distr_and_collider/collider/collider.json

  # Distribution in the normalized xy space
  particle_file: ../1_build_distr_and_collider/particles/00.parquet

  # Initial off-momentum
  delta_max: 27.e-5

  # Tracking
  n_turns: 1000            # number of turns to track

  # Beam to track
  beam: lhcb1   #lhcb1 or lhcb2

# Save collider or not
dump_collider: false
dump_config_in_collider: false

# Log
log_file: tree_maker.log
